name: Linux

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CC: gcc-12
      CXX: g++-12

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Ubuntu packages
      run: |
        sudo apt update
        sudo apt -y install libjansson-dev libzimg-dev nasm ninja-build

    - name: Install Python packages
      run: |
        python -m pip install -U pip
        pip install -U cython meson setuptools wheel

    - name: Install VapourSynth
      run: |
        git clone https://github.com/vapoursynth/vapoursynth.git --depth 1
        pushd vapoursynth
        ./autogen.sh
        ./configure --prefix=/usr
        make -j2
        sudo make install -j2
        pip install .
        popd
        rm -rf vapoursynth

    - name: Install FFmpeg
      run: |
        git clone https://git.ffmpeg.org/ffmpeg.git --depth 1
        pushd ffmpeg
        ./configure --prefix=/usr --enable-gpl --enable-version3 --disable-static --enable-shared --disable-programs --disable-doc --disable-avdevice --disable-swresample --disable-postproc --disable-avfilter --disable-encoders --disable-muxers --disable-debug
        make -j2
        sudo make install -j2
        popd
        rm -rf ffmpeg

    - name: Download libp2p
      run: |
        git clone https://github.com/sekrit-twc/libp2p.git --depth 1

    - name: Build
      run: |
        meson setup build
        ninja -C build
